### ISSUE TITLE
NullPointerException on Player Logout game event.

### ISSUE THREAD

**Issue by Vaygrim** [rafradek/Mods#16]
This is with v1.0.4 'Alpha' of the "GrimCo R&D" Mod Pack available on Curse / the Twitch Launcher.

[https://gist.github.com/Vaygrim/3690949acecc35ebf4b8581cfe2a01d3](url)

**Comment by Vaygrim** [comment]
[01:08:21] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent@48fede0c:
java.lang.NullPointerException: null
	at rafradek.TF2weapons.TF2EventsCommon.cleanPlayer(TF2EventsCommon.java:810) ~[TF2EventsCommon.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_300_TF2EventsCommon_cleanPlayer_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:578) [FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:387) [pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849) [pa.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:456) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[01:08:21] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[01:08:21] [Server thread/ERROR] [FML]: 0: NORMAL
[01:08:21] [Server thread/ERROR] [FML]: 1: ASM: crafttweaker.mc1120.events.CommonEventHandler@6e5e6530 onPlayerLoggedOut(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[01:08:21] [Server thread/ERROR] [FML]: 2: ASM: baubles.common.event.EventHandlerEntity@54c63ee9 onPlayerLoggedOut(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[01:08:21] [Server thread/ERROR] [FML]: 3: ASM: rafradek.TF2weapons.TF2EventsCommon@72d1ba26 cleanPlayer(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[01:08:21] [Server thread/ERROR] [FML]: 4: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerNetwork@14d7ec9d onLogout(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[01:08:21] [Server thread/ERROR] [FML]: 5: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@e1fd3e loggedOutEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[01:08:21] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at rafradek.TF2weapons.TF2EventsCommon.cleanPlayer(TF2EventsCommon.java:810) ~[TF2EventsCommon.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_300_TF2EventsCommon_cleanPlayer_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:578) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:387) ~[pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849) ~[pa.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:456) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[01:08:21] [Server thread/ERROR]: This crash report has been saved to: /home/15498/userdata/minecraft/./crash-reports/crash-2017-12-16_01.08.21-server.txt
[01:08:21] [Server thread/INFO]: Stopping server
[01:08:21] [Server thread/INFO]: Saving players
[01:08:21] [Server thread/WARN]: handleDisconnection() called twice
[01:08:21] [Server thread/INFO]: Saving worlds
[01:08:21] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[01:08:21] [Server thread/INFO]: Saving chunks for level 'world'/the_nether
[01:08:21] [Server thread/INFO]: Saving chunks for level 'world'/the_end
[01:08:21] [Server thread/INFO]: Saving chunks for level 'world'/L3Factory
[01:08:21] [Server thread/INFO]: Saving chunks for level 'world'/L2Factory
[01:08:21] [Server thread/INFO]: Saving chunks for level 'world'/L1Factory
[01:08:21] [Server thread/INFO]: Saving chunks for level 'world'/Storage Cell
[01:08:21] [Server thread/INFO] [FML]: Unloading dimension 0
[01:08:21] [Server thread/INFO] [FML]: Unloading dimension -1
[01:08:21] [Server thread/INFO] [FML]: Unloading dimension 1
[01:08:21] [Server thread/INFO] [FML]: Unloading dimension 1703
[01:08:21] [Server thread/INFO] [FML]: Unloading dimension 1702
[01:08:21] [Server thread/INFO] [FML]: Unloading dimension 1701
[01:08:21] [Server thread/INFO] [FML]: Unloading dimension 2
[01:08:21] [Server thread/INFO] [FML]: Applying holder lookups
[01:08:21] [Server thread/INFO] [FML]: Holder lookups applied
[01:08:22] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[01:08:22] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[01:08:22] [Server Shutdown Thread/INFO]: Stopping server
[01:08:22] [Server Shutdown Thread/INFO]: Saving players
Exception in thread "Server Shutdown Thread"

**Comment by rafradek** [comment]
You are using an outdated version
