### ISSUE TITLE
Server crash when launched (1.5.10 ver)

### ISSUE THREAD

**Issue by Shootlife** [rafradek/Mods#58]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
    at rafradek.TF2weapons.common.MapList.initMaps(MapList.java:86) ~[MapList.class:?]
    at rafradek.TF2weapons.TF2weapons.preinit(TF2weapons.java:543) ~[TF2weapons.class:?]

**Comment by triggerhurt** [comment]
Experiencing the same error on a freshly installed Forge 1.12.2 14.23.5.2837 server, with mod version 1.5.10. Server does not crash with version 1.5.9.2. Crash log: https://pastebin.com/uwwu6CJe
Error appears to occur regardless of whether or not it's the only mod on the server.
Client seems to work fine, just the server.

**Comment by rafradek** [comment]
should be fixed this time

**Comment by triggerhurt** [comment]
Yeah, that did it. Thanks!
