### ISSUE TITLE
playerdata gets corrupted when picking up sandvich, internal server error

### ISSUE THREAD

**Issue by ghost** [rafradek/Mods#60]
This happened suddenly when I used the missing texture block that creates custom robots, it never happened before and only started after I crashed the first time. Every time after that, if I pick up a sandvich, i get kicked and it says internal server error. This only started happening after I tried to put a sandvich in the weapon section for the robot creator block. If you can fix this asap so I don't have to delete my playerdata every time I pick up a sandvich, I will be grateful.

Log:
`[22:45:41 [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /60.240.184.37:13827]
net.minecraft.util.ReportedException: Ticking player
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.CooldownTracker.func_185142_b(Lnet/minecraft/item/Item;)V
    at rafradek.TF2weapons.TF2EventsCommon.pickAmmo(TF2EventsCommon.java:1597) ~[TF2EventsCommon.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_TF2EventsCommon_pickAmmo_EntityItemPickupEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
    at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:513) ~[ForgeEventFactory.class:?]
    at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:396) ~[acl.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:600) ~[aed.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:571) ~[aed.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) ~[vp.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
    ... 9 more`

**Comment by FoxyTails1987** [comment]
Im having that stupid problem too
