### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by fedheadphone** [rafradek/Mods#65]
I am unsure if this is the result of a mod incompatibility, but here it is.

PMDescription: Ticking entity

java.lang.NullPointerException: Ticking entity
	at rafradek.TF2weapons.entity.mercenary.EntityTF2Character.isValidTarget(EntityTF2Character.java:1090)
	at rafradek.TF2weapons.entity.mercenary.EntityTF2Character$$Lambda$3638/2089287138.apply(Unknown Source)
	at rafradek.TF2weapons.entity.ai.EntityAINearestChecked$1.apply(EntityAINearestChecked.java:44)
	at rafradek.TF2weapons.entity.ai.EntityAINearestChecked$1.apply(EntityAINearestChecked.java:41)
	at net.minecraft.world.chunk.Chunk.func_177430_a(Chunk.java:936)
	at net.minecraft.world.World.func_175647_a(World.java:3085)
	at rafradek.TF2weapons.entity.ai.EntityAINearestChecked.func_75250_a(EntityAINearestChecked.java:94)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:760)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at rafradek.TF2weapons.entity.mercenary.EntityTF2Character.func_70636_d(EntityTF2Character.java:555)
	at rafradek.TF2weapons.entity.mercenary.EntitySoldier.func_70636_d(EntitySoldier.java:152)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at rafradek.TF2weapons.entity.mercenary.EntityTF2Character.func_70071_h_(EntityTF2Character.java:1376)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rafradek** [comment]
Disable mercenaries attacking other mobs to prevent this from happening

**Comment by fedheadphone** [comment]
That seems to have worked. Thank you for the assistance!
