### ISSUE TITLE
Hitscan and some Projectiles fail to hit the Enemy

### ISSUE THREAD

**Issue by EnderIzzy124** [rafradek/Mods#67]
Howdy! I've loved your mod for a long while now. It greatly emulates TF2's mechanics in a Sandbox environment. Time to build my own maps. ;) (my only complaint is that some weapons and items are ugly, but as I've been using the mod on and off for a while now, that's been improving. If you need help with that, let me know. I would send you improved models for free, I love this mod.)

Anyway, I'm currently using the latest build on Curseforge (rafradek_tf2_weapons-1.12.2-1.6.1) and for whatever reason, Hitscan weapons (currently tested with the Widowmaker,  Stock Shotgun, and Stock Minigun) don't hit the enemy.

Currently installed mods -
- antique atlas 4.5.1
- AutoRegLib 1.3-32
- BetterFPS 1.4.8
- betterportals 0.3.7.1
- Biomes O Plenty 7.0.1.2441
- CarryOn v1.12.3
- Chisel 1.0.1.44
- Clumps 3.1.2
- conarm 1.2.5.3
- ContainerFix v1.0
- coroutil 1.2.32
- CTM 1.0.0.29
- Dynamic Surroundings 3.6.0.2
- Dynamic Trees 0.9.6
- Dynamic Trees BOP 1.4.1e
- Enchantment Descriptions 1.1.15
- engineers_doors 0.8.0
- Fast Leaf Decay v14
- foamfix 0.10.5
- Forgelin 1.8.4
- G.L.A.S.S 7.0.0
- iChunUtil 7.2.2
- Immersive Engineer 0.12-92
- IronBackpacks 3.0.8-12
- IvToolkit 1.3.3
- jei 4.15.0.291
- jer 0.9.2.60
- Klee Slabs 5.4.12
- LetSleepingDogsLie 1.0.2
- Mantle 1.3.3.55
- Mapmaker's Gadgets 1.2
- Multimine
- Orelib 3.6.0.1
- Placebo 1.6.0
- QuarkOddities
- Quark r1.6-177
- **Rafradek_tf2_weapons 1.6.1**
- RandomThings 4.2.7.3
- Realistic Torches 2.1.1
- Recurrent Complex 1.4.8.2
- Scaling Health 1.3.40+145
- SilentLib 3.0.13+167
- stg 1.2.3
- TConstruct 2.13.0.171
- Tickrate Changer 1.0.14
- TinkerToolLeveling 1.1.0
- Toast+Control 1.8.1
- Trumpetskeleton 1.0.2.1
- Valkyrien Skeis 1.0 Alpha-1
- VanillaFix 10.10-99
- Weather2 2.6.12
- xpfromharvest 1.1.0
- xptome v1.1.1

I would provide a crash log.... but there is none. However, when I fire a weapon (in this case, the windowmaker) it does spit this out.

`03:51:31.570
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
03:51:31.570
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: java.lang.Exception: Tried getting entities from giant bounding box of box[1046.9378013258581, 24.320604149942397, -400.006357833474 -> 1261.0954819153212, 69.62000000476837, -255.46615295995548]
03:51:31.570
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at net.minecraft.world.World.func_175674_a(World.java:5851)
03:51:31.570
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at net.minecraft.world.World.func_72839_b(World.java:3006)
03:51:31.571
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at rafradek.TF2weapons.util.TF2Util.pierce(TF2Util.java:177)
03:51:31.571
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at rafradek.TF2weapons.item.ItemBulletWeapon.shoot(ItemBulletWeapon.java:250)
03:51:31.586
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at rafradek.TF2weapons.item.ItemWeapon.use(ItemWeapon.java:224)
03:51:31.586
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at rafradek.TF2weapons.item.ItemBulletWeapon.use(ItemBulletWeapon.java:113)
03:51:31.586
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at rafradek.TF2weapons.common.WeaponsCapability.stateDo(WeaponsCapability.java:1093)
03:51:31.586
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at rafradek.TF2weapons.client.TF2EventsClient.keyPressUpdate(TF2EventsClient.java:480)
03:51:31.586
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at rafradek.TF2weapons.client.TF2EventsClient.keyPressUpdate(TF2EventsClient.java:425)
03:51:31.586
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at rafradek.TF2weapons.client.TF2EventsClient.renderTick(TF2EventsClient.java:1145)
03:51:31.586
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_605_TF2EventsClient_renderTick_RenderTickEvent.invoke(.dynamic)
03:51:31.586
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
03:51:31.586
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
03:51:31.586
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:360)
03:51:31.587
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1123)
03:51:31.587
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
03:51:31.587
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
03:51:31.587
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:51:31.587
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:51:31.587
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:51:31.587
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at java.lang.reflect.Method.invoke(Method.java:497)
03:51:31.587
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
03:51:31.587
game
[03:51:31] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5852]: 	at `

If anything else is needed, let me know. I'm hoping this is just a minor bug, rather than a mod incompatibility.

**Comment by EnderIzzy124** [comment]
Hello again! Couldn't access github for a while (dunno why) so I could update this. Had to go on the discord.
After some testing, I have determined that this mod is incompatible with Valkeryian Warfare. Hope a fix gets put out soon, but take your time.
