### ISSUE TITLE
Mod doesn't work with galacticraft

### ISSUE THREAD

**Issue by Joshua8965** [rafradek/Mods#9]
I have been experimenting and Tf2 stuff doesn't seem to be compatible with galacticraft

**Comment by rafradek** [comment]
There is nothing to be done without further explaination

**Comment by Joshua8965** [comment]
How about this crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.118.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/16/17 7:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from TF2 Stuff Mod (rafradek_tf2_weapons)
Caused by: java.lang.ExceptionInInitializerError
	at rafradek.TF2weapons.TF2weapons.init(TF2weapons.java:732)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at rafradek.TF2weapons.ItemFromData.getNewStack(ItemFromData.java:98)
	at rafradek.TF2weapons.TF2Achievements.<clinit>(TF2Achievements.java:24)
	... 37 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 549838448 bytes (524 MB) / 1655414784 bytes (1578 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHI	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHI	architecturecraft{1.5.0.0} [ArchitectureCraft] (ArchitectureCraft-Mod-1.10.2.jar) 
	UCHI	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCHI	customnpcs{1.10.2} [CustomNPCs] (Custom-NPCs-Mod-1.10.2.jar) 
	UCHI	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.1_1.10.2.jar) 
	UCHI	props{2.4.1} [Decocraft] (Decocraft-2.4.1_1.10.2.jar) 
	UCHI	exoticbirds{1.0} [Exotic Birds] (Exotic Birds 1.10.2-1.4.0.jar) 
	UCHI	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.118.jar) 
	UCHI	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.118.jar) 
	UCHI	grimoireofgaia{1.5.6} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.10.2-1.5.6.jar) 
	UCHI	keywizard{1.10.2-1.4.5} [Keyboard Wizard] (keywizard-1.10.2-1.4.5.jar) 
	UCHI	monsteranddungeons{0.1} [Monsters and Dungeons] (Monsters-and-Dungeons-Mod-1.10.2.jar) 
	UCHE	rafradek_tf2_weapons{1.0.8.4} [TF2 Stuff Mod] (rafradek_tf2_weapons-1.10.2-1.0.8.4.jar) 
	UCHI	flammpfeil.slashblade{mc1.10.2-r37} [SlashBlade] (SlashBlade-Mod-1.10.2.jar) 
	UCHI	tails{1.10.2-1.8.4} [Tails] (Tails-1.10.2-1.8.4.jar) 
	UCHI	XaeroMinimap{1.13.5} [Xaero's Minimap] (Xaeros-Minimap-Mod-1.10.2.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.118.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4599' Renderer: 'Intel(R) HD Graphics 630'

**Comment by rafradek** [comment]
This is fixed already, but only for 1.11.2 or above
